services:
  postgres-partition-1:
    image: postgres:17.0
    container_name: saga-pg1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - /data/postgres:/data/postgres

  postgres-partition-2:
    image: postgres:17.0
    container_name: saga-pg2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: db
    ports:
      - 5433:5432
    volumes:
      - /data/postgres:/data/postgres
