services:
  postgres-partition-1:
    image: postgres:17.0
    container_name: saga-pg1
    env_file:
      - .env.local
    ports:
      - 5432:5432
    volumes:
      - /data/postgres:/data/postgres

  postgres-partition-2:
    image: postgres:17.0
    container_name: saga-pg2
    env_file:
      - .env.local
    ports:
      - 5433:5432
    volumes:
      - /data/postgres:/data/postgres

  redis:
    image: redis/redis-stack
    container_name: saga-redis
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis-data:/data/redis

volumes:
  redis-data:
