services:
  wallet-service:
    container_name: wallet-service
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env.example
    ports:
      - 3000:3000

  postgres-partition-1:
    image: postgres:17.0
    container_name: saga-pg1
    ports:
      - 5432:5432
    env_file:
      - .env.example
    volumes:
      - /data/postgres:/data/postgres

  postgres-partition-2:
    image: postgres:17.0
    container_name: saga-pg2
    ports:
      - 5433:5432
    env_file:
      - .env.example
    volumes:
      - /data/postgres:/data/postgres

  redis:
    image: redis/redis-stack
    container_name: saga-redis
    ports:
      - 6379:6379
      - 8001:8001
    env_file:
      - .env.example
    volumes:
      - redis-data:/data/redis

volumes:
  redis-data:
