services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    ports:
      - 3000:3000

  command-service:
    container_name: command-service
    build:
      context: .
      dockerfile: ./apps/command-service/Dockerfile
    ports:
      - 3001:3000

  projection-service:
    container_name: projection-service
    build:
      context: .
      dockerfile: ./apps/projection-service/Dockerfile
    ports:
      - 3002:3000

  query-service:
    container_name: query-service
    build:
      context: .
      dockerfile: ./apps/query-service/Dockerfile
    ports:
      - 3003:3000

  postgres-partition-1:
    image: postgres:17.0
    container_name: event-driven-cqrs-pg1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: db
    ports:
      - 5434:5432
    volumes:
      - /data/postgres:/data/postgres

  postgres-partition-2:
    image: postgres:17.0
    container_name: event-driven-cqrs-pg2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: db
    ports:
      - 5435:5432
    volumes:
      - /data/postgres:/data/postgres

  kafka:
    image: apache/kafka-native:4.0.1
    container_name: kafka
    ports:
      - 9092:9092

  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis-data:/data/redis

volumes:
  redis-data:
