services:
  postgres-partition-1:
    image: postgres:17.0
    container_name: event-driven-cqrs-pg1
    env_file:
      - .env.local
    ports:
      - 5434:5432
    volumes:
      - /data/postgres:/data/postgres

  postgres-partition-2:
    image: postgres:17.0
    container_name: event-driven-cqrs-pg2
    env_file:
      - .env.local
    ports:
      - 5435:5432
    volumes:
      - /data/postgres:/data/postgres

  postgres-event-store:
    image: postgres:17.0
    container_name: event-driven-cqrs-event-store-pg
    env_file:
      - .env.local
    ports:
      - 5436:5432
    volumes:
      - /data/postgres:/data/postgres

  rabbit:
    image: rabbitmq:3.13.3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - 6380:6379
      - 8001:8001
    volumes:
      - redis-data:/data/redis

volumes:
  redis-data:
