services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    env_file:
      - .env.example
    ports:
      - 3001:3001

  command-service:
    container_name: command-service
    build:
      context: .
      dockerfile: ./apps/command-service/Dockerfile
    env_file:
      - .env.example
    ports:
      - 3002:3002

  projection-service:
    container_name: projection-service
    build:
      context: .
      dockerfile: ./apps/projection-service/Dockerfile
    env_file:
      - .env.example
    ports:
      - 3003:3003

  query-service:
    container_name: query-service
    build:
      context: .
      dockerfile: ./apps/query-service/Dockerfile
    env_file:
      - .env.example
    ports:
      - 3004:3004

  postgres-partition-1:
    image: postgres:17.0
    container_name: event-driven-cqrs-pg1
    ports:
      - 5434:5432
    env_file:
      - .env.example
    volumes:
      - /data/postgres:/data/postgres

  postgres-partition-2:
    image: postgres:17.0
    container_name: event-driven-cqrs-pg2
    ports:
      - 5435:5432
    env_file:
      - .env.example
    volumes:
      - /data/postgres:/data/postgres

  postgres-event-store:
    image: postgres:17.0
    container_name: event-driven-cqrs-event-store-pg
    ports:
      - 5436:5432
    env_file:
      - .env.example
    volumes:
      - /data/postgres:/data/postgres

  rabbit:
    image: rabbitmq:3.13.3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis-data:/data/redis

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9095:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '4001:3000'
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  redis-data:
  grafana-data:
