services:
  postgres-partition-1:
    image: postgres:17.0
    container_name: event-driven-cqrs-pg1
    ports:
      - 5434:5432
    volumes:
      - /data/postgres:/data/postgres

  postgres-partition-2:
    image: postgres:17.0
    container_name: event-driven-cqrs-pg2
    ports:
      - 5435:5432
    volumes:
      - /data/postgres:/data/postgres

  postgres-event-store:
    image: postgres:17.0
    container_name: event-driven-cqrs-event-store-pg
    ports:
      - 5436:5432
    volumes:
      - /data/postgres:/data/postgres

  kafka:
    image: apache/kafka-native:4.0.1
    container_name: kafka
    ports:
      - 9092:9092

  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - 6380:6379
      - 8001:8001
    volumes:
      - redis-data:/data/redis

volumes:
  redis-data:
